In [16]:
import numpy as np
import random

In [8]:
a = np.array([1,2,3,4])
b = [1,2,3]

In [14]:
print(a)
print(b)

[1 2 3 4]
[1, 2, 3]


In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
#one directional array
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.random.rand(2,2)

array([[0.22785012, 0.26746592],
       [0.55187524, 0.10586904]])

In [22]:
#3-colums and 4 shape
np.random.randint(0, 5, (3,4))

array([[1, 2, 0, 2],
       [0, 3, 1, 1],
       [3, 3, 2, 4]])

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.linspace(0,20,200, endpoint=False)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9,
       11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. ,
       12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1,
       13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2,
       14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15

In [37]:
np.arange(0,20,0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9,
       11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. ,
       12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1,
       13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2,
       14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15

In [44]:
a = np.array([[1,2,3],[5,6,7]])
a
b = a.shape
b

(2, 3)

In [54]:
#Array Attributes
b = np.random.randint(0,10,[3,4])
print(b[1,2])
print(b[1])
print(b[:,0])
print(b[1,:])
print(b[1, 1:3])
b

5
[0 1 5 3]
[9 0 8]
[0 1 5 3]
[1 5]


array([[9, 8, 4, 0],
       [0, 1, 5, 3],
       [8, 8, 3, 1]])

In [56]:
a = np.random.randint(0,10, [10,10])
a

array([[0, 7, 1, 5, 6, 1, 6, 2, 7, 8],
       [1, 1, 0, 8, 7, 9, 8, 9, 1, 0],
       [1, 1, 4, 7, 6, 8, 1, 7, 4, 9],
       [8, 8, 6, 2, 5, 8, 6, 2, 5, 9],
       [5, 3, 0, 8, 0, 7, 2, 4, 9, 9],
       [6, 7, 3, 8, 2, 9, 5, 0, 3, 4],
       [1, 0, 8, 9, 8, 3, 4, 4, 7, 1],
       [4, 8, 2, 6, 3, 4, 5, 9, 2, 7],
       [1, 6, 9, 2, 1, 0, 7, 1, 7, 9],
       [8, 0, 3, 8, 9, 4, 0, 1, 4, 5]])

In [57]:
a[3:6, 2:7]

array([[6, 2, 5, 8, 6],
       [0, 8, 0, 7, 2],
       [3, 8, 2, 9, 5]])

In [58]:
a[3:6, 2:]

array([[6, 2, 5, 8, 6, 2, 5, 9],
       [0, 8, 0, 7, 2, 4, 9, 9],
       [3, 8, 2, 9, 5, 0, 3, 4]])

In [59]:
a = np.random.randint([2,3, 3])
a

array([0, 1, 0])

In [62]:
a = np.random.randint(0,10, [2,3, 3])
a


array([[[9, 0, 0],
        [9, 0, 0],
        [5, 3, 3]],

       [[2, 1, 9],
        [8, 5, 6],
        [0, 2, 3]]])

In [65]:
a[1, 1, :]


array([8, 5, 6])

In [67]:
a[1]=99
a

array([[[ 9,  0,  0],
        [ 9,  0,  0],
        [ 5,  3,  3]],

       [[99, 99, 99],
        [99, 99, 99],
        [99, 99, 99]]])

In [69]:
a[2: 1] = [100, 200]
a

ValueError: could not broadcast input array from shape (2,) into shape (0,3,3)

In [75]:
a = np.array([2,3,3,0,7])
b = np.array([1,2,3,5,9])
print(a+b)
print(a*b)
print(a*10)
print(a**2)

[ 3  5  6  5 16]
[ 2  6  9  0 63]
[20 30 30  0 70]
[ 4  9  9  0 49]


In [76]:
np.sqrt(a)

array([1.41421356, 1.73205081, 1.73205081, 0.        , 2.64575131])

In [77]:
np.min(a)

0

In [79]:
np.log(a)

C:\Users\Namratha Kaipa\AppData\Local\Temp\ipykernel_24760\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([0.69314718, 1.09861229, 1.09861229,       -inf, 1.94591015])

In [80]:
np.std(a)

2.280350850198276

In [81]:
a<2

array([False, False, False,  True, False])

In [82]:
a<10

array([ True,  True,  True,  True,  True])

In [83]:
(a<2).astype(int)

array([0, 0, 0, 1, 0])

In [91]:
a= np.random.randint(0,10,(3,4))
print(a)
print(a<3)

[[0 7 9 8]
 [0 6 4 5]
 [7 1 2 6]]
[[ True False False False]
 [ True False False False]
 [False  True  True False]]


In [92]:
np.where(a>2)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([1, 2, 3, 1, 2, 3, 0, 3], dtype=int64))

In [93]:
len(np.where(a>2))

2

In [94]:
type(np.where(a>2))

tuple

In [96]:
##Stacking splitting
a = np.array([1,2,3,4,5,6])
type(a)

numpy.ndarray

In [98]:
a = [1,2,3]
b=[4,5,6]
print(a+b)

[1, 2, 3, 4, 5, 6]


In [116]:
a= np.array([1,2,3],[2,3,4])
b= np.array([4,5,6],[2,3,4])
c= np.array([8,9,0],[7,8,3])
#np.concatenate((a,b,c), axis=1)

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [117]:
## must work on this code.

In [120]:
a= np.random.randint(0,10,[2,3])
b= np.random.randint(0,10,[2,4])
c= np.random.randint(0,10,[2,7])
np.hstack((a,b,c))

array([[5, 9, 3, 5, 3, 5, 8, 5, 8, 6, 4, 2, 8, 6],
       [6, 6, 1, 0, 1, 3, 2, 5, 8, 2, 4, 4, 2, 6]])

In [121]:
np.split(a,2)

[array([[5, 9, 3]]), array([[6, 6, 1]])]

In [122]:
a.ndim

2

In [125]:
a = np.random.randint(0,10,[2,3,4])

In [127]:
a

array([[[2, 6, 4, 1],
        [2, 9, 5, 4],
        [1, 9, 0, 1]],

       [[0, 0, 6, 7],
        [3, 8, 5, 5],
        [4, 8, 1, 5]]])

In [128]:
a.ndim

3

In [129]:
a.shape

(2, 3, 4)

In [130]:
np.mean(a)

4.0

In [131]:
np.max(a)

9

In [132]:
np.absolute(a)

array([[[2, 6, 4, 1],
        [2, 9, 5, 4],
        [1, 9, 0, 1]],

       [[0, 0, 6, 7],
        [3, 8, 5, 5],
        [4, 8, 1, 5]]])

In [133]:
np.mean(a, axis=0)

array([[1. , 3. , 5. , 4. ],
       [2.5, 8.5, 5. , 4.5],
       [2.5, 8.5, 0.5, 3. ]])

In [134]:
np.mean(a, axis=1)

array([[1.66666667, 8.        , 3.        , 2.        ],
       [2.33333333, 5.33333333, 4.        , 5.66666667]])

In [135]:
np.mean(a, axis=0).ndim

2

In [137]:
np.mean(a, axis=-1)

array([[3.25, 5.  , 2.75],
       [3.25, 5.25, 4.5 ]])

In [141]:
#Array Sorting
a= np.random.randint(0,10,(4,4))
b = np.sort(a)
c = np.sort(a, axis=0)
print(a)
print(b)
print(c)

[[7 7 1 1]
 [7 3 0 9]
 [8 0 3 2]
 [4 3 7 3]]
[[1 1 7 7]
 [0 3 7 9]
 [0 2 3 8]
 [3 3 4 7]]
[[4 0 0 1]
 [7 3 1 2]
 [7 3 3 3]
 [8 7 7 9]]


In [143]:
sort_index = np.argsort(a[:, 0])
print(sort_index)

[3 0 1 2]


In [144]:
e = a[sort_index]
print(e)

[[4 3 7 3]
 [7 7 1 1]
 [7 3 0 9]
 [8 0 3 2]]
