In [17]:
import numpy as np

In [18]:
marks=np.random.randint(0,101, size=(10,4))
print('Marks of Students:\n',marks)

Marks of Students:
 [[29 61  9 93]
 [48 78 30 25]
 [ 5 14 44 20]
 [ 9  5 83  3]
 [82 35 58 19]
 [29 17 78 16]
 [85 17 20  4]
 [84 27 23 82]
 [27 19 84  3]
 [68 83 41  7]]


In [19]:
total_marks = np.sum(marks, axis=1)
print("Total marks of Each Student: \n ", total_marks)

Total marks of Each Student: 
  [192 181  83 100 194 140 126 216 133 199]


In [20]:
sorted_indices = np.argsort(total_marks)
sorted_marks = marks[sorted_indices]
print("sorted Marks of students based of total marks\n", sorted_marks)

sorted Marks of students based of total marks
 [[ 5 14 44 20]
 [ 9  5 83  3]
 [85 17 20  4]
 [27 19 84  3]
 [29 17 78 16]
 [48 78 30 25]
 [29 61  9 93]
 [82 35 58 19]
 [68 83 41  7]
 [84 27 23 82]]


In [21]:
sorted_total_marks = total_marks[sorted_indices]
print("\n Sorted Total Marks: \n", sorted_total_marks)


 Sorted Total Marks: 
 [ 83 100 126 133 140 181 192 194 199 216]
